# Generated by Django 2.2.5 on 2019-09-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='project_id',
            field=models.IntegerField(max_length=20, verbose_name='项目名称'),
        ),
    ]
